[View in Colaboratory](https://colab.research.google.com/github/geotana/UdacityDL/blob/master/%E5%AD%A6%E7%BF%92%E3%83%A1%E3%83%A2.ipynb)

In [3]:
import numpy as np
target_vector = [0,2,1,3,4,0]               # クラス分類を整数値のベクトルで表現したもの
n_labels = len(target_vector)  # 分類クラスの数 = 5
# n_labels = len(np.unique(target_vector))  # 分類クラスの数 = 5
np.eye(n_labels)[target_vector]  

array([[1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0.]])

In [1]:
import tensorflow as tf

labels = tf.placeholder(tf.int64, [None])
y_ = tf.one_hot(labels, depth=3, dtype=tf.float32)
z0_ = tf.argmax(y_,0)  
z1_ = tf.argmax(y_,1)  

with tf.Session() as sess:
  sess.run(tf.initialize_all_variables())
  teacher = [1, 2, 0, 2]
  out= sess .run(y_, feed_dict={labels: teacher})
  print(out)
  out = sess.run(z0_, feed_dict={labels: teacher})
  print(out)
  out = sess.run(z1_, feed_dict={labels: teacher})
  print(out)
  

Instructions for updating:
Use `tf.global_variables_initializer` instead.
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]]
[2 0 1]
[1 2 0 2]


In [0]:
import numpy as np
import tensorflow as tf
bs = 2
voc = 4
em = 3

final_embeddings_np_voc_em = np.ones( (voc, em))
np_bs_em = np.full((em, voc), 2.0 )

np_bs_voc = np.zeros( shape= (bs, voc) , dtype = float )
argmax_1 = np.argmax( (final_embeddings_np_voc_em).T @ np_bs_em[1,:])
np_bs_voc[1, argmax_1] = 1.0

print( "final_embeddings_np_voc_em", final_embeddings_np_voc_em)
print( "np_bs_em", np_bs_em)
print( "np_bs_voc", np_bs_voc)

final_embeddings_np_voc_em [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
np_bs_em [[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
np_bs_voc [[0. 0. 0. 0.]
 [1. 0. 0. 0.]]


In [0]:
str_list = ['python', 'list', 'exchange']
print( ','.join(str_list))
print( "".join(str_list))

python,list,exchange
pythonlistexchange


In [0]:
import numpy as np
na = np.array([ [1,2,3], [2,4,8] ])
print(na)
print(np.argmax(na,axis=0)) #[[2][2][2]]
print(np.argmax(na)) #[[2][2][2]]
print(np.argmax(na,axis=1))#[[3],[3]
              

[[1 2 3]
 [2 4 8]]
[1 1 1]
5
[2 2]


In [0]:
import tensorflow as tf

a = tf.constant(0, name='const1') #定数a
b = tf.Variable(0, name='val1') #変数b

# aとbを足す
add = tf.add(a,b)
#変数bに足した結果をアサイン
assign = tf.assign(b, add)
c = tf.placeholder(tf.int32, name='input') #入力c
# アサインした結果とcを掛け算
mul = tf.multiply(assign, c)
#変数の初期化
init = tf.global_variables_initializer()

with tf.Session() as sess:
    #初期化を実行
    sess.run(init)
    for i in range(3):
        # 掛け算を計算するまでのループを実行
        print(sess.run(mul, feed_dict={a:3, c:3}))

9
18
27


In [0]:
import numpy as np
b=np.array ([[1,2]]) 
print(np.sum(b, 1)[:, None],np.sum(b, 1)[:, None].shape)
print(np.sum(b, 1),np.sum(b, 1).shape)
print(b/np.sum(b, 1)[:, None])
print(b/np.sum(b, 1))


[[3]] (1, 1)
[3] (1,)
[[0.33333333 0.66666667]]
[[0.33333333 0.66666667]]


In [0]:
names = ['Alice', 'Bob', 'Charlie']
ages = (24, 50, 18)

z = zip(names, ages)
print(z)
print(list(z))

[('Alice', 24), ('Bob', 50), ('Charlie', 18)]


In [0]:
# ＜ブロードキャスト＞
# 形状が1 x　2　と　2 x　1の配列の演算でも、
# ブロードキャストが適用され2 x2の配列として演算されます。
import numpy as np
x=np.array ([[1,2]]) 
y=np.array ([[1,1],
              [0,1]])
print(x.shape)
print(y.shape)
print(x+y)

In [0]:
import numpy as np

print(np.array([1,2]).shape) #2,  普通の1次元ベクトル表現
print(np.array([[1,2]]).shape) #1,2　横ベクトル
print(np.array([[1,2]]).T.shape) #2,1　縦ベクトル
print(np.array([[1],[2]]).shape) #2,1　縦ベクトル
print()
print(np.array([[1,2,3],[1,2,3]]).shape) #2,3
print(np.array([[1,2,3],[1,2,3]]).T.shape) #3,2
print( np.array([ [1,2,3], [1,2,3] ]) @ np.array([[1],[2],[3]])  ) # OK
#print(np.matmul( [ [1,2,3], [1,2,3] ] , [[1,2,3]] ) ) # error
print(np.matmul( [ [1,2,3], [1,2,3] ] , [1,2,3] ) ) #
print(np.array( [ [1,2,3], [1,2,3] ] ) @ np.array( [1,2,3] ) ) #
# NumPyではベクトルを1 次元配列と2 次元配列のどちらでも表せます。
# 2 次元配列で表 すなら、n 次の行ベクトル（横ベクトル) は1 x　2 次元配列、
# 縦ベクト ル) は1　x 2 次元配列とします。
# 1 次元配列では行ベクトルと列ベクトルを明確に区別はできません。

# @演算子やdot 関数を使う際には一つ注意点があります。これらは二つの配列の次元が異 
# なる場合でも演算ができてしまいます2 次元配列と1 次元配列との演算では。例えば、
# 内部で1次元配列を2 次元配列（列ベクトル) に拡大して計算し、結果は1次元配列に戻して返す
print()
print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]]).shape) #2,2,3
print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])) 
print()

print(np.array([[[1,2,3],[4,5,6]]]).shape) #1,2,3
print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]])) 
print()

print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]]).T.shape) #2,2,3
print(np.array([[[1,2,3],[4,5,6]],[[7,8,9],[11,12,13]]]).T) 
print()
print(np.array([[[1,2,3],[1,2,3]],[[1,2,3],[1,2,3]]]).T.shape) #2,2,3
print()
print(np.arange(6).reshape((-1))) #=> array([[0, 1, 2, 3, 4, 5]])
print(np.arange(6).reshape((1, -1))) #=> array([[0, 1, 2, 3, 4, 5]])
print(np.arange(6).reshape((-1, 1))) #=> array([[0],[1],[2],[3],[4],[5]])
print(np.arange(6).reshape((2, -1))) #=> array([[0, 1, 2],[3, 4, 5]])

(2,)
(1, 2)
(2, 1)
(2, 1)

(2, 3)
(3, 2)
[[14]
 [14]]
[14 14]
[14 14]

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]

(1, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]

(3, 2, 2)
[[[ 1  7]
  [ 4 11]]

 [[ 2  8]
  [ 5 12]]

 [[ 3  9]
  [ 6 13]]]

(3, 2, 2)

[0 1 2 3 4 5]
[[0 1 2 3 4 5]]
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
[[0 1 2]
 [3 4 5]]
